### ISSUE TITLE
 163 candidate genes

### ISSUE THREAD

**Issue by qyzhu0627** [julienrichardalbert/5mC-H3K27me3#1]
Hi Julien Richard Albert,
Very amazing jobs! We are interseted in 163 candidate genes that appeared to require 5mC deposition and/or H3K27me3 depletion for their activation in differentiated cells, could you provide the table of 163 candidate genes?

**Comment by julienrichardalbert** [comment]
Hello! You can find the list of 163 genes and their associated putative 5mC-H3K27me3 regulatory region here:
[activating_SWRS.bed](https://github.com/julienrichardalbert/5mC-H3K27me3/blob/main/activating_SWRs.bed)

**Comment by qyzhu0627** [comment]
Thanks, I only find 132 genes in activating_SWRs.bed?

**Comment by julienrichardalbert** [comment]
Huh, you're right, I must have filtered it or something.
Here's the list of 163 genes:
[163_genes_and_their_SWR.txt](https://github.com/julienrichardalbert/5mC-H3K27me3/blob/main/163_genes_and_their_SWR.txt)
sorry about that!

**Comment by qyzhu0627** [comment]
Thanks!
